name: win-msbuild-actions-workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          # cc: clang
          # cxx: clang++
          build-type: Release
          # Extra options pass to cmake while configuring project
          # configure-options: -DCMAKE_C_FLAGS=-w32 -DPNG_INCLUDE=OFF
          # run-test: true
          # ctest-options: -R mytest
          # install the build using cmake --install
          # install-build: true
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 14
        
      - name: Run 
        run: ./winapi-helloworld.exe
        working-directory: build/Release
        
